In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install openai
!pip install python-dotenv

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.32.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 447, in run
    conflicts = self._determine_conflicts(to_install)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/commands/install.py", line 578, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/operations/check.py", line 42, in create_package_set_from_installed
    dependencies = list(dist.iter_dependencies())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/metadata/importlib/_dists.py", line 219, in iter_dependencies
    for req_string in self.metadata.get_all("Requires-Dist", []):
                      ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 982, in __get__
    def __get__(self, instance, owner=None):

KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/usr/local/lib/python3.12/dist-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1674, in print
    renderables = self._collect_renderables(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1553, in _collect_renderables
    check_text()
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/console.py", line 1531, in check_text
    append(sep_text.join(text))
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/text.py", line 803, in join
    for text in iter_text():
                ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/rich/text.py", line 788, in iter_text
    def iter_text() -> Iterable["Text"]:

KeyboardInterrupt
^C
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)

In [ ]:
!pip install transformers
!pip install torch
!pip install huggingface_hub
!pip install evaluate
!pip install datasets

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (1.11.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface_hub) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface_hub) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub) (0.1.2)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)

# GPT data collection and checking the performance on the data with fine-tuned roberta

# dataset install making question for gpt input

In [ ]:
from datasets import load_dataset

# Load a custom CSV file
data_files = {"train": "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/full_data.csv"}
dataset = load_dataset("csv", data_files=data_files)

In [ ]:
# dataset into pandas dataframe
import pandas as pd
df = dataset['train'].to_pandas()

In [ ]:
# remove duplicate answers
df_check = df.drop_duplicates("human_answers")

In [ ]:
import nltk
from nltk.lm import Vocabulary
nltk.download('punkt_tab')# using nltk word tokenizer
# checking the number of tokens of the text and , if it is less than 4, remove the rows
def check_length(sentence):
    tokenized_sentence = nltk.tokenize.word_tokenize(str(sentence))
    return len(tokenized_sentence)
# remove duplicates and less than 4 tokens of texts.
def preprocess_data(df):
  df = df.drop_duplicates(subset = ["human_answers"])
  df['length'] = df["human_answers"].apply(check_length)
  df = df[df['length'] > 3]
  df = df[["question", "length", "source"]]
  return df
df_processed = preprocess_data(df)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
/tmp/ipykernel_13609/1483159615.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['length'] = df["human_answers"].apply(check_length)

In [ ]:
# checking category distribution
def check_category_numbers(df):
  answers = []
  sources_list = ['reddit_eli5', 'open_qa', 'wiki_csai','medicine','finance']
  for source in sources_list:
    a = df[(df["source"] == source)].dropna()
    number = len(a)
    answers.append([source, number])
  return pd.DataFrame(answers, columns = [["source", "number"]])

check_category_numbers(df_processed)

        source number
0  reddit_eli5  45965
1      open_qa   1170
2    wiki_csai    771
3     medicine   1244
4      finance   3932

In [ ]:
# making list to make the inputs for GPT-5.4-mini extraction
gpt_input = []
for question, length in zip(df_processed["question"], df_processed["length"]):
  gpt_input.append([question, length])

# GPT 5.4 answer extraction

In [ ]:
import os
from google.colab import userdata
from openai import OpenAI

# getting own openAI API key
api_key = userdata.get('OPEN')
os.environ['OPENAI_API_KEY'] = api_key
AI_generated = []
client = OpenAI()

i = 1
# for loop to extract GPT5.4-mini answers
for question, length in gpt_input:
  # manually setting system input and question input
  developer_input = 'answer the question by using only sentences not structured forms.'

  # using length because the length distribution of texts become close to human's answers
  question_input = question + ' Absolutely do not use more than ' + str(length - 4) + ' words'
  response = client.responses.create(
    model= "gpt-5.4-mini",
    input= [
        {
            'role': "developer",
            'content': developer_input,
        },
        {
            'role': "user",
            'content': question_input,
        },
    ],
  )
  #AI_generated list stores question of the data and answers from GPT5.4 - mini
  AI_generated.append([question, response.output_text])
  print(str(i) + ' times' )
  i = i+1

Streaming output truncated to the last 5000 lines.
7080 times
7081 times
7082 times
7083 times
7084 times
7085 times
7086 times
7087 times
7088 times
7089 times
7090 times
7091 times
7092 times
7093 times
7094 times
7095 times
7096 times
7097 times
7098 times
7099 times
7100 times
7101 times
7102 times
7103 times
7104 times
7105 times
7106 times
7107 times
7108 times
7109 times
7110 times
7111 times
7112 times
7113 times
7114 times
7115 times
7116 times
7117 times
7118 times
7119 times
7120 times
7121 times
7122 times
7123 times
7124 times
7125 times
7126 times
7127 times
7128 times
7129 times
7130 times
7131 times
7132 times
7133 times
7134 times
7135 times
7136 times
7137 times
7138 times
7139 times
7140 times
7141 times
7142 times
7143 times
7144 times
7145 times
7146 times
7147 times
7148 times
7149 times
7150 times
7151 times
7152 times
7153 times
7154 times
7155 times
7156 times
7157 times
7158 times
7159 times
7160 times
7161 times
7162 times
7163 times
7164 times
7165 times
7166 times
7167 times
7168 times
7169 times
7170 times
7171 times
7172 times
7173 times
7174 times
7175 times
7176 times
7177 times
7178 times
7179 times
7180 times
7181 times
7182 times
7183 times
7184 times
7185 times
7186 times
7187 times
7188 times
7189 times
7190 times
7191 times
7192 times
7193 times
7194 times
7195 times
7196 times
7197 times
7198 times
7199 times
7200 times
7201 times
7202 times
7203 times
7204 times
7205 times
7206 times
7207 times
7208 times
7209 times
7210 times
7211 times
7212 times
7213 times
7214 times
7215 times
7216 times
7217 times
7218 times
7219 times
7220 times
7221 times
7222 times
7223 times
7224 times
7225 times
7226 times
7227 times
7228 times
7229 times
7230 times
7231 times
7232 times
7233 times
7234 times
7235 times
7236 times
7237 times
7238 times
7239 times
7240 times
7241 times
7242 times
7243 times
7244 times
7245 times
7246 times
7247 times
7248 times
7249 times
7250 times
7251 times
7252 times
7253 times
7254 times
7255 times
7256 times
7257 times
7258 times
7259 times
7260 times
7261 times
7262 times
7263 times
7264 times
7265 times
7266 times
7267 times
7268 times
7269 times
7270 times
7271 times
7272 times
7273 times
7274 times
7275 times
7276 times
7277 times
7278 times
7279 times
7280 times
7281 times
7282 times
7283 times
7284 times
7285 times
7286 times
7287 times
7288 times
7289 times
7290 times
7291 times
7292 times
7293 times
7294 times
7295 times
7296 times
7297 times
7298 times
7299 times
7300 times
7301 times
7302 times
7303 times
7304 times
7305 times
7306 times
7307 times
7308 times
7309 times
7310 times
7311 times
7312 times
7313 times
7314 times
7315 times
7316 times
7317 times
7318 times
7319 times
7320 times
7321 times
7322 times
7323 times
7324 times
7325 times
7326 times
7327 times
7328 times
7329 times
7330 times
7331 times
7332 times
7333 times
7334 times
7335 times
7336 times
7337 times
7338 times
7339 times
7340 times
7341 times
7342 times
7343 times
7344 times
7345 times
7346 times
7347 times
7348 times
7349 times
7350 times
7351 times
7352 times
7353 times
7354 times
7355 times
7356 times
7357 times
7358 times
7359 times
7360 times
7361 times
7362 times
7363 times
7364 times
7365 times
7366 times
7367 times
7368 times
7369 times
7370 times
7371 times
7372 times
7373 times
7374 times
7375 times
7376 times
7377 times
7378 times
7379 times
7380 times
7381 times
7382 times
7383 times
7384 times
7385 times
7386 times
7387 times
7388 times
7389 times
7390 times
7391 times
7392 times
7393 times
7394 times
7395 times
7396 times
7397 times
7398 times
7399 times
7400 times
7401 times
7402 times
7403 times
7404 times
7405 times
7406 times
7407 times
7408 times
7409 times
7410 times
7411 times
7412 times
7413 times
7414 times
7415 times
7416 times
7417 times
7418 times
7419 times
7420 times
7421 times
7422 times
7423 times
7424 times
7425 times
7426 times
7427 times
7428 times
7429 times
7430 times
7431 times
7432 times
7433 times
7434 times
7435 times
7436 times
7437 times
7438 times
7439 times
7440 times
7441 times
7442 times
7443 times
7444 times
7445 times
7446 times
7447 times
7448 times
7449 times
7450 times
7451 times
7452 times
7453 times
7454 times
7455 times
7456 times
7457 times
7458 times
7459 times
7460 times
7461 times
7462 times
7463 times
7464 times
7465 times
7466 times
7467 times
7468 times
7469 times
7470 times
7471 times
7472 times
7473 times
7474 times
7475 times
7476 times
7477 times
7478 times
7479 times
7480 times
7481 times
7482 times
7483 times
7484 times
7485 times
7486 times
7487 times
7488 times
7489 times
7490 times
7491 times
7492 times
7493 times
7494 times
7495 times
7496 times
7497 times
7498 times
7499 times
7500 times
7501 times
7502 times
7503 times
7504 times
7505 times
7506 times
7507 times
7508 times
7509 times
7510 times
7511 times
7512 times
7513 times
7514 times
7515 times
7516 times
7517 times
7518 times
7519 times
7520 times
7521 times
7522 times
7523 times
7524 times
7525 times
7526 times
7527 times
7528 times
7529 times
7530 times
7531 times
7532 times
7533 times
7534 times
7535 times
7536 times
7537 times
7538 times
7539 times
7540 times
7541 times
7542 times
7543 times
7544 times
7545 times
7546 times
7547 times
7548 times
7549 times
7550 times
7551 times
7552 times
7553 times
7554 times
7555 times
7556 times
7557 times
7558 times
7559 times
7560 times
7561 times
7562 times
7563 times
7564 times
7565 times
7566 times
7567 times
7568 times
7569 times
7570 times
7571 times
7572 times
7573 times
7574 times
7575 times
7576 times
7577 times
7578 times
7579 times
7580 times
7581 times
7582 times
7583 times
7584 times
7585 times
7586 times
7587 times
7588 times
7589 times
7590 times
7591 times
7592 times
7593 times
7594 times
7595 times
7596 times
7597 times
7598 times
7599 times
7600 times
7601 times
7602 times
7603 times
7604 times
7605 times
7606 times
7607 times
7608 times
7609 times
7610 times
7611 times
7612 times
7613 times
7614 times
7615 times
7616 times
7617 times
7618 times
7619 times
7620 times
7621 times
7622 times
7623 times
7624 times
7625 times
7626 times
7627 times
7628 times
7629 times
7630 times
7631 times
7632 times
7633 times
7634 times
7635 times
7636 times
7637 times
7638 times
7639 times
7640 times
7641 times
7642 times
7643 times
7644 times
7645 times
7646 times
7647 times
7648 times
7649 times
7650 times
7651 times
7652 times
7653 times
7654 times
7655 times
7656 times
7657 times
7658 times
7659 times
7660 times
7661 times
7662 times
7663 times
7664 times
7665 times
7666 times
7667 times
7668 times
7669 times
7670 times
7671 times
7672 times
7673 times
7674 times
7675 times
7676 times
7677 times
7678 times
7679 times
7680 times
7681 times
7682 times
7683 times
7684 times
7685 times
7686 times
7687 times
7688 times
7689 times
7690 times
7691 times
7692 times
7693 times
7694 times
7695 times
7696 times
7697 times
7698 times
7699 times
7700 times
7701 times
7702 times
7703 times
7704 times
7705 times
7706 times
7707 times
7708 times
7709 times
7710 times
7711 times
7712 times
7713 times
7714 times
7715 times
7716 times
7717 times
7718 times
7719 times
7720 times
7721 times
7722 times
7723 times
7724 times
7725 times
7726 times
7727 times
7728 times
7729 times
7730 times
7731 times
7732 times
7733 times
7734 times
7735 times
7736 times
7737 times
7738 times
7739 times
7740 times
7741 times
7742 times
7743 times
7744 times
7745 times
7746 times
7747 times
7748 times
7749 times
7750 times
7751 times
7752 times
7753 times
7754 times
7755 times
7756 times
7757 times
7758 times
7759 times
7760 times
7761 times
7762 times
7763 times
7764 times
7765 times
7766 times
7767 times
7768 times
7769 times
7770 times
7771 times
7772 times
7773 times
7774 times
7775 times
7776 times
7777 times
7778 times
7779 times
7780 times
7781 times
7782 times
7783 times
7784 times
7785 times
7786 times
7787 times
7788 times
7789 times
7790 times
7791 times
7792 times
7793 times
7794 times
7795 times
7796 times
7797 times
7798 times
7799 times
7800 times
7801 times
7802 times
7803 times
7804 times
7805 times
7806 times
7807 times
7808 times
7809 times
7810 times
7811 times
7812 times
7813 times
7814 times
7815 times
7816 times
7817 times
7818 times
7819 times
7820 times
7821 times
7822 times
7823 times
7824 times
7825 times
7826 times
7827 times
7828 times
7829 times
7830 times
7831 times
7832 times
7833 times
7834 times
7835 times
7836 times
7837 times
7838 times
7839 times
7840 times
7841 times
7842 times
7843 times
7844 times
7845 times
7846 times
7847 times
7848 times
7849 times
7850 times
7851 times
7852 times
7853 times
7854 times
7855 times
7856 times
7857 times
7858 times
7859 times
7860 times
7861 times
7862 times
7863 times
7864 times
7865 times
7866 times
7867 times
7868 times
7869 times
7870 times
7871 times
7872 times
7873 times
7874 times
7875 times
7876 times
7877 times
7878 times
7879 times
7880 times
7881 times
7882 times
7883 times
7884 times
7885 times
7886 times
7887 times
7888 times
7889 times
7890 times
7891 times
7892 times
7893 times
7894 times
7895 times
7896 times
7897 times
7898 times
7899 times
7900 times
7901 times
7902 times
7903 times
7904 times
7905 times
7906 times
7907 times
7908 times
7909 times
7910 times
7911 times
7912 times
7913 times
7914 times
7915 times
7916 times
7917 times
7918 times
7919 times
7920 times
7921 times
7922 times
7923 times
7924 times
7925 times
7926 times
7927 times
7928 times
7929 times
7930 times
7931 times
7932 times
7933 times
7934 times
7935 times
7936 times
7937 times
7938 times
7939 times
7940 times
7941 times
7942 times
7943 times
7944 times
7945 times
7946 times
7947 times
7948 times
7949 times
7950 times
7951 times
7952 times
7953 times
7954 times
7955 times
7956 times
7957 times
7958 times
7959 times
7960 times
7961 times
7962 times
7963 times
7964 times
7965 times
7966 times
7967 times
7968 times
7969 times
7970 times
7971 times
7972 times
7973 times
7974 times
7975 times
7976 times
7977 times
7978 times
7979 times
7980 times
7981 times
7982 times
7983 times
7984 times
7985 times
7986 times
7987 times
7988 times
7989 times
7990 times
7991 times
7992 times
7993 times
7994 times
7995 times
7996 times
7997 times
7998 times
7999 times
8000 times
8001 times
8002 times
8003 times
8004 times
8005 times
8006 times
8007 times
8008 times
8009 times
8010 times
8011 times
8012 times
8013 times
8014 times
8015 times
8016 times
8017 times
8018 times
8019 times
8020 times
8021 times
8022 times
8023 times
8024 times
8025 times
8026 times
8027 times
8028 times
8029 times
8030 times
8031 times
8032 times
8033 times
8034 times
8035 times
8036 times
8037 times
8038 times
8039 times
8040 times
8041 times
8042 times
8043 times
8044 times
8045 times
8046 times
8047 times
8048 times
8049 times
8050 times
8051 times
8052 times
8053 times
8054 times
8055 times
8056 times
8057 times
8058 times
8059 times
8060 times
8061 times
8062 times
8063 times
8064 times
8065 times
8066 times
8067 times
8068 times
8069 times
8070 times
8071 times
8072 times
8073 times
8074 times
8075 times
8076 times
8077 times
8078 times
8079 times
8080 times
8081 times
8082 times
8083 times
8084 times
8085 times
8086 times
8087 times
8088 times
8089 times
8090 times
8091 times
8092 times
8093 times
8094 times
8095 times
8096 times
8097 times
8098 times
8099 times
8100 times
8101 times
8102 times
8103 times
8104 times
8105 times
8106 times
8107 times
8108 times
8109 times
8110 times
8111 times
8112 times
8113 times
8114 times
8115 times
8116 times
8117 times
8118 times
8119 times
8120 times
8121 times
8122 times
8123 times
8124 times
8125 times
8126 times
8127 times
8128 times
8129 times
8130 times
8131 times
8132 times
8133 times
8134 times
8135 times
8136 times
8137 times
8138 times
8139 times
8140 times
8141 times
8142 times
8143 times
8144 times
8145 times
8146 times
8147 times
8148 times
8149 times
8150 times
8151 times
8152 times
8153 times
8154 times
8155 times
8156 times
8157 times
8158 times
8159 times
8160 times
8161 times
8162 times
8163 times
8164 times
8165 times
8166 times
8167 times
8168 times
8169 times
8170 times
8171 times
8172 times
8173 times
8174 times
8175 times
8176 times
8177 times
8178 times
8179 times
8180 times
8181 times
8182 times
8183 times
8184 times
8185 times
8186 times
8187 times
8188 times
8189 times
8190 times
8191 times
8192 times
8193 times
8194 times
8195 times
8196 times
8197 times
8198 times
8199 times
8200 times
8201 times
8202 times
8203 times
8204 times
8205 times
8206 times
8207 times
8208 times
8209 times
8210 times
8211 times
8212 times
8213 times
8214 times
8215 times
8216 times
8217 times
8218 times
8219 times
8220 times
8221 times
8222 times
8223 times
8224 times
8225 times
8226 times
8227 times
8228 times
8229 times
8230 times
8231 times
8232 times
8233 times
8234 times
8235 times
8236 times
8237 times
8238 times
8239 times
8240 times
8241 times
8242 times
8243 times
8244 times
8245 times
8246 times
8247 times
8248 times
8249 times
8250 times
8251 times
8252 times
8253 times
8254 times
8255 times
8256 times
8257 times
8258 times
8259 times
8260 times
8261 times
8262 times
8263 times
8264 times
8265 times
8266 times
8267 times
8268 times
8269 times
8270 times
8271 times
8272 times
8273 times
8274 times
8275 times
8276 times
8277 times
8278 times
8279 times
8280 times
8281 times
8282 times
8283 times
8284 times
8285 times
8286 times
8287 times
8288 times
8289 times
8290 times
8291 times
8292 times
8293 times
8294 times
8295 times
8296 times
8297 times
8298 times
8299 times
8300 times
8301 times
8302 times
8303 times
8304 times
8305 times
8306 times
8307 times
8308 times
8309 times
8310 times
8311 times
8312 times
8313 times
8314 times
8315 times
8316 times
8317 times
8318 times
8319 times
8320 times
8321 times
8322 times
8323 times
8324 times
8325 times
8326 times
8327 times
8328 times
8329 times
8330 times
8331 times
8332 times
8333 times
8334 times
8335 times
8336 times
8337 times
8338 times
8339 times
8340 times
8341 times
8342 times
8343 times
8344 times
8345 times
8346 times
8347 times
8348 times
8349 times
8350 times
8351 times
8352 times
8353 times
8354 times
8355 times
8356 times
8357 times
8358 times
8359 times
8360 times
8361 times
8362 times
8363 times
8364 times
8365 times
8366 times
8367 times
8368 times
8369 times
8370 times
8371 times
8372 times
8373 times
8374 times
8375 times
8376 times
8377 times
8378 times
8379 times
8380 times
8381 times
8382 times
8383 times
8384 times
8385 times
8386 times
8387 times
8388 times
8389 times
8390 times
8391 times
8392 times
8393 times
8394 times
8395 times
8396 times
8397 times
8398 times
8399 times
8400 times
8401 times
8402 times
8403 times
8404 times
8405 times
8406 times
8407 times
8408 times
8409 times
8410 times
8411 times
8412 times
8413 times
8414 times
8415 times
8416 times
8417 times
8418 times
8419 times
8420 times
8421 times
8422 times
8423 times
8424 times
8425 times
8426 times
8427 times
8428 times
8429 times
8430 times
8431 times
8432 times
8433 times
8434 times
8435 times
8436 times
8437 times
8438 times
8439 times
8440 times
8441 times
8442 times
8443 times
8444 times
8445 times
8446 times
8447 times
8448 times
8449 times
8450 times
8451 times
8452 times
8453 times
8454 times
8455 times
8456 times
8457 times
8458 times
8459 times
8460 times
8461 times
8462 times
8463 times
8464 times
8465 times
8466 times
8467 times
8468 times
8469 times
8470 times
8471 times
8472 times
8473 times
8474 times
8475 times
8476 times
8477 times
8478 times
8479 times
8480 times
8481 times
8482 times
8483 times
8484 times
8485 times
8486 times
8487 times
8488 times
8489 times
8490 times
8491 times
8492 times
8493 times
8494 times
8495 times
8496 times
8497 times
8498 times
8499 times
8500 times
8501 times
8502 times
8503 times
8504 times
8505 times
8506 times
8507 times
8508 times
8509 times
8510 times
8511 times
8512 times
8513 times
8514 times
8515 times
8516 times
8517 times
8518 times
8519 times
8520 times
8521 times
8522 times
8523 times
8524 times
8525 times
8526 times
8527 times
8528 times
8529 times
8530 times
8531 times
8532 times
8533 times
8534 times
8535 times
8536 times
8537 times
8538 times
8539 times
8540 times
8541 times
8542 times
8543 times
8544 times
8545 times
8546 times
8547 times
8548 times
8549 times
8550 times
8551 times
8552 times
8553 times
8554 times
8555 times
8556 times
8557 times
8558 times
8559 times
8560 times
8561 times
8562 times
8563 times
8564 times
8565 times
8566 times
8567 times
8568 times
8569 times
8570 times
8571 times
8572 times
8573 times
8574 times
8575 times
8576 times
8577 times
8578 times
8579 times
8580 times
8581 times
8582 times
8583 times
8584 times
8585 times
8586 times
8587 times
8588 times
8589 times
8590 times
8591 times
8592 times
8593 times
8594 times
8595 times
8596 times
8597 times
8598 times
8599 times
8600 times
8601 times
8602 times
8603 times
8604 times
8605 times
8606 times
8607 times
8608 times
8609 times
8610 times
8611 times
8612 times
8613 times
8614 times
8615 times
8616 times
8617 times
8618 times
8619 times
8620 times
8621 times
8622 times
8623 times
8624 times
8625 times
8626 times
8627 times
8628 times
8629 times
8630 times
8631 times
8632 times
8633 times
8634 times
8635 times
8636 times
8637 times
8638 times
8639 times
8640 times
8641 times
8642 times
8643 times
8644 times
8645 times
8646 times
8647 times
8648 times
8649 times
8650 times
8651 times
8652 times
8653 times
8654 times
8655 times
8656 times
8657 times
8658 times
8659 times
8660 times
8661 times
8662 times
8663 times
8664 times
8665 times
8666 times
8667 times
8668 times
8669 times
8670 times
8671 times
8672 times
8673 times
8674 times
8675 times
8676 times
8677 times
8678 times
8679 times
8680 times
8681 times
8682 times
8683 times
8684 times
8685 times
8686 times
8687 times
8688 times
8689 times
8690 times
8691 times
8692 times
8693 times
8694 times
8695 times
8696 times
8697 times
8698 times
8699 times
8700 times
8701 times
8702 times
8703 times
8704 times
8705 times
8706 times
8707 times
8708 times
8709 times
8710 times
8711 times
8712 times
8713 times
8714 times
8715 times
8716 times
8717 times
8718 times
8719 times
8720 times
8721 times
8722 times
8723 times
8724 times
8725 times
8726 times
8727 times
8728 times
8729 times
8730 times
8731 times
8732 times
8733 times
8734 times
8735 times
8736 times
8737 times
8738 times
8739 times
8740 times
8741 times
8742 times
8743 times
8744 times
8745 times
8746 times
8747 times
8748 times
8749 times
8750 times
8751 times
8752 times
8753 times
8754 times
8755 times
8756 times
8757 times
8758 times
8759 times
8760 times
8761 times
8762 times
8763 times
8764 times
8765 times
8766 times
8767 times
8768 times
8769 times
8770 times
8771 times
8772 times
8773 times
8774 times
8775 times
8776 times
8777 times
8778 times
8779 times
8780 times
8781 times
8782 times
8783 times
8784 times
8785 times
8786 times
8787 times
8788 times
8789 times
8790 times
8791 times
8792 times
8793 times
8794 times
8795 times
8796 times
8797 times
8798 times
8799 times
8800 times
8801 times
8802 times
8803 times
8804 times
8805 times
8806 times
8807 times
8808 times
8809 times
8810 times
8811 times
8812 times
8813 times
8814 times
8815 times
8816 times
8817 times
8818 times
8819 times
8820 times
8821 times
8822 times
8823 times
8824 times
8825 times
8826 times
8827 times
8828 times
8829 times
8830 times
8831 times
8832 times
8833 times
8834 times
8835 times
8836 times
8837 times
8838 times
8839 times
8840 times
8841 times
8842 times
8843 times
8844 times
8845 times
8846 times
8847 times
8848 times
8849 times
8850 times
8851 times
8852 times
8853 times
8854 times
8855 times
8856 times
8857 times
8858 times
8859 times
8860 times
8861 times
8862 times
8863 times
8864 times
8865 times
8866 times
8867 times
8868 times
8869 times
8870 times
8871 times
8872 times
8873 times
8874 times
8875 times
8876 times
8877 times
8878 times
8879 times
8880 times
8881 times
8882 times
8883 times
8884 times
8885 times
8886 times
8887 times
8888 times
8889 times
8890 times
8891 times
8892 times

In [ ]:
#into dataframe and save for future use
df_new_gpt = pd.DataFrame(AI_generated, columns = ['question','gpt_5_4_mini'])
df_new_gpt.to_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini.csv', index = True)

# creating gpt5.4-mini dataset from stored files into test, val, and train sets

In [ ]:
# getting all of the gpt answer file and unify them
recent_gpt_path_1 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini1.csv"
recent_gpt_path_2 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini2.csv"
recent_gpt_path_3 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini3.csv"
recent_gpt_path_4 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini4.csv"
recent_gpt_path_5 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini5.csv"
recent_gpt_path_6 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini6.csv"
recent_gpt_path_7 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini7.csv"
recent_gpt_path_8 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini8.csv"
recent_gpt_path_9 = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/gpt-5.4_mini9.csv"

# original dataset for creating new dataset of human and gpt5.4-mini generated dataset
test_path = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/test.csv"
val_path = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/val.csv"
train_path = "/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/train.csv"

In [ ]:
import pandas as pd
# all of the dataset into pandas dataframe
df_test = pd.read_csv(test_path)
df_val = pd.read_csv(val_path)
df_train = pd.read_csv(train_path)

df_recent_1 = pd.read_csv(recent_gpt_path_1)
df_recent_2 = pd.read_csv(recent_gpt_path_2)
df_recent_3 = pd.read_csv(recent_gpt_path_3)
df_recent_4 = pd.read_csv(recent_gpt_path_4)
df_recent_5 = pd.read_csv(recent_gpt_path_5)
df_recent_6 = pd.read_csv(recent_gpt_path_6)
df_recent_7 = pd.read_csv(recent_gpt_path_7)
df_recent_8 = pd.read_csv(recent_gpt_path_8)
df_recent_9 = pd.read_csv(recent_gpt_path_9)

In [ ]:
# unify all of the gpt5.4-mini data, adding label as 1, and rename the columns into text and label
new_data = pd.concat([df_recent_1,df_recent_2,df_recent_3,df_recent_4,df_recent_5, df_recent_6, df_recent_7, df_recent_8, df_recent_9])[['gpt_5_4_mini']]
df_recent = new_data.assign(label = 1)
df_recent = df_recent[['gpt_5_4_mini', 'label']].rename(columns= {'gpt_5_4_mini' : 'text'})

In [ ]:
# test set
test_data = pd.concat([df_recent.iloc[0:4596], df_recent.iloc[45965:46082], df_recent.iloc[47135:47212], df_recent.iloc[47906:48030], df_recent.iloc[49150:49543]])
test_data

                                                  text  label
0    Because “#1 New York Times Best Seller” is not...      1
1    Because “New York Times #1 Best Seller” is not...      1
2    Because “#1 best seller” is often used for dif...      1
3    We use road salt because it melts ice, making ...      1
4    We use salt on roads because it helps melt ice...      1
..                                                 ...    ...
338  Not automatically. A 52-week high can mean str...      1
339  In India, the interest component of a personal...      1
340  Yes, generally lower interest rates can encour...      1
341  It can be a bad idea, but it is not always a d...      1
342  Usually, no. Dividend quotes for U.S. stocks g...      1

[5307 rows x 2 columns]

In [ ]:
# validation set
val_data = pd.concat([df_recent.iloc[4596:9192], df_recent.iloc[46082:46199], df_recent.iloc[47212:47289], df_recent.iloc[48030:48154], df_recent.iloc[49543:49936]])
val_data

                                                   text  label
4596  IQ tests are like a ruler for some kinds of th...      1
4597  IQ tests are kind of like a ruler for certain ...      1
4598  IQ tests are fairly good at measuring a person...      1
4599  A fever is your body making itself hotter to h...      1
4600  A fever is your body’s way of fighting germs, ...      1
...                                                 ...    ...
731   Yes, you can usually use credit card points to...      1
732   Contractors can often recoup taxation-related ...      1
733   A good rule is to keep the car payment at or b...      1
734   You can use your current home’s equity as part...      1
735   Could you please consider a credit decrease on...      1

[5307 rows x 2 columns]

In [ ]:
# train set
train_data = pd.concat([df_recent.iloc[9192:45965], df_recent.iloc[46199:47135], df_recent.iloc[47289:47906], df_recent.iloc[48154:49150], df_recent.iloc[49936:53082]])
train_data

                                                   text  label
9192  Guys often wake up with an erection because du...      1
9193  Morning erections happen because sleep changes...      1
9194  Guys often wake up with an erection because th...      1
9195  The Illuminati and Freemasons are often mixed ...      1
9196  They are secretive groups once made of wealthy...      1
...                                                 ...    ...
1477  Yes, some blood pressure change within an hour...      1
1478  A painless lump near the shoulder could be a b...      1
1479  Acutret is isotretinoin, and it should only be...      1
1480  Yes. A pulse around 35 with dizziness and shor...      1
1481  No, severe back pain at 18 is not something to...      1

[42468 rows x 2 columns]

In [ ]:
# getting only human data from test, val, and train data
df_test = df_test.loc[df_test['label'] == 0]
df_val = df_val.loc[df_val['label']==0]
df_train = df_train.loc[df_train['label']==0]

In [ ]:
# creating the new dataset by unifying human and gpt5.4- mini dataset for each train, val, and test.
new_test = pd.concat([df_test,test_data])[['text', 'label']]
new_val = pd.concat([df_val,val_data])[['text', 'label']]
new_train = pd.concat([df_train,train_data])[['text', 'label']]

In [ ]:
# store the data as files
new_test.to_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/new_test.', index = False)
new_val.to_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/new_val.', index = False)
new_train.to_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/new_train.', index = False)

In [ ]:
# store the full data including questions and answers from GPT5.4 for further analysis
new_full_data = pd.concat([df_recent_1,df_recent_2,df_recent_3,df_recent_4,df_recent_5, df_recent_6, df_recent_7, df_recent_8, df_recent_9])[['question', 'gpt_5_4_mini']]
new_full_data.to_csv('/content/drive/MyDrive/Colab Notebooks/NLU_project/HC3_dataset/new_full_data.', index = False)